//! Enhanced collectors. Privileged sources are started only through explicit controls.
#[cfg(target_os = "windows")]
pub mod baseline;
#[cfg(target_os = "windows")]
pub mod clock_bridge;
#[cfg(target_os = "windows")]
pub mod cpu_read;
#[cfg(target_os = "windows")]
pub mod cpu_service;
pub mod disk_io;
#[cfg(target_os = "windows")]
pub mod disk_service;
pub mod disk_snapshot;
#[cfg(target_os = "windows")]
pub mod enumeration;
pub mod etw_decode;
pub mod event_order;
#[cfg(target_os = "windows")]
pub mod gpu_read;
#[cfg(target_os = "windows")]
pub mod gpu_temperature;
#[cfg(target_os = "windows")]
pub mod identity;
#[cfg(target_os = "windows")]
pub mod live_identity;
#[cfg(target_os = "windows")]
pub mod pipe;
#[cfg(target_os = "windows")]
pub mod pipeline;
#[cfg(target_os = "windows")]
pub mod probe;
pub mod protocol;
#[cfg(target_os = "windows")]
pub mod storage_service;
#[cfg(target_os = "windows")]
pub mod temperature_history;
#[cfg(target_os = "windows")]
pub mod trace_run;
